Revert "Break the program: results in: thread '<main>' panicked at 'arithmetic operation overflowed', src/conway.rs:46"
This reverts commit e49e82cb01b8180940cc6dece7f564b3251557d7.

It breaks it because we can't go lower than 0 on a usize :-)